{{- if and .Values.database.createSecret (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: financeservice-database
type: Opaque
stringData:
  ConnectionStrings__FinanceDatabase: {{ .Values.database.connectionString | quote }}
{{- end }}
