variables:
- name: serviceName
  value: orderservice
- name: pipelineArtifactName
  value: $(serviceName)
- name: folderNameComponent
  value: 'order'
- name: folderNameService
  value: 'OrderService'
- name: dockerRepositoryName
  value: $(serviceName)
- name: versionTagPrefix
  value: 'orderservice'

