variables:
- name: serviceName
  value: frontendcustomerorderstatus
- name: pipelineArtifactName
  value: $(serviceName)
- name: folderNameComponent
  value: 'frontendcustomerorderstatus'
- name: folderNameService
  value: 'FrontendCustomerOrderStatus'
- name: dockerRepositoryName
  value: $(serviceName)
- name: versionTagPrefix
  value: 'frontendcustomerorderstatus'

