variables:
- name: serviceName
  value: frontendkitchenmonitor
- name: pipelineArtifactName
  value: $(serviceName)
- name: folderNameComponent
  value: 'frontendkitchenmonitor'
- name: folderNameService
  value: 'FrontendKitchenMonitor'
- name: dockerRepositoryName
  value: $(serviceName)
- name: versionTagPrefix
  value: 'frontendkitchenmonitor'

