variables:
- name: serviceName
  value: frontendselfservicepos
- name: pipelineArtifactName
  value: $(serviceName)
- name: folderNameComponent
  value: 'frontendselfservicepos'
- name: folderNameService
  value: 'FrontendSelfServicePos'
- name: dockerRepositoryName
  value: $(serviceName)
- name: versionTagPrefix
  value: 'frontendselfservicepos'

