variables:
- name: serviceName
  value: kitchenservice
- name: pipelineArtifactName
  value: $(serviceName)
- name: folderNameComponent
  value: 'kitchen'
- name: folderNameService
  value: 'KitchenService'
- name: dockerRepositoryName
  value: $(serviceName)
- name: versionTagPrefix
  value: 'kitchen'

