image:
  repository: __azureContainerRegistry__/frontendkitchenmonitor
  tag: __artifactVersion__

ingress:
  enabled: enabled
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster
  hosts:
    - host: kitchenmonitor.fastfood.staging.aksdemo.4tecture.ch
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: frontendkitchenmonitor-tls
      hosts:
        - kitchenmonitor.fastfood.staging.aksdemo.4tecture.ch