{{- if .Values.demosecret.enabled }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: fastfood-secrets
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
scopes:
  - orderservice
{{- end }}
