{{- $root := . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "daprenv.fullname" $root }}-dapr-secrets
data:
  redis-password: {{ .Values.dapr.redisPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: demo
data:
  sample: {{ .Values.demosecret.samplevalue | b64enc }}