{{- $root := . }}
{{- if and .Values.dapr.createRedisSecret (not .Values.dapr.existingRedisSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "daprenv.fullname" $root }}-dapr-secrets
type: Opaque
stringData:
  redis-password: {{ .Values.dapr.redisPassword | quote }}
{{- end }}
{{- if .Values.demosecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: demo
type: Opaque
stringData:
  sample: {{ .Values.demosecret.samplevalue | quote }}
{{- end }}
