apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: fastfood-secrets
  namespace: fastfood
spec:
  type: secretstores.local.file
  version: v1  
  metadata:
  - name: secretsFile
    value: ../components/secrets.json
  - name: nestedSeparator
    value: "."
scopes:
  - orderservice
  - kitchenservice
  - financeservice
  - orderserviceactors