name: ci-frontendcustomerorderstatus

trigger:
  branches:
    include:
      - main
      - release/*
  paths:
    include:
      - src/services/frontendcustomerorderstatus/**

variables:
  - template: config/var-commonvariables.yml
  - template: config/var-frontendcustomerorderstatus.yml

jobs:
  - template: build/job-buildcontainerizedservice.yml
    parameters:
      displayName: "Build Frontend Customer Order Status Service"
      dockerFile: '$(dockerFilePath)'
      dockerRepositoryName: '$(dockerRepositoryName)'
      chartPath: '$(helmChartSourcePath)'
      artifactName: '$(pipelineArtifactName)'
      azureContainerRegistryServiceConnection: '$(azureContainerRegistryServiceConnection)'
      netCoreAspNetVersion: '$(netCoreAspNetVersion)'
      netCoreSdkVersion: '$(netCoreSdkVersion)'
      helmVersion: '$(helmVersion)'
      artifactStagingDirectory: '$(Build.ArtifactStagingDirectory)'
      buildContext: '$(Build.SourcesDirectory)/src'
      buildId: '$(Build.BuildId)'
      buildNumber: '$(Build.BuildNumber)'
      servicePaths:
        - '$(componentPath)'
      serviceTagPrefix: '$(versionTagPrefix)'
      installMonotag: true
      updateBuildNumber: true
      nugetFeeds: []
      publishArtifacts:
        - dockerfileTarget: "test"
          imageLabel: "testresults"
          directoryToCopy: "/testresults"
          artifactName: "testresults"
          publishType: "testResults"
      dockerArguments: '--build-arg IMAGE_NET_ASPNET_VERSION=$(netCoreAspNetVersion) --build-arg IMAGE_NET_SDK_VERSION=$(netCoreSdkVersion)'