apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
    name: fastfood-secrets
    namespace: fastfood
spec:
    type: secretstores.kubernetes
    version: v1
    metadata:
    - name: namespace
    value: fastfood
    scopes:
    - orderservice
    - kitchenservice
    - financeservice
    - orderserviceactors
    - frontendselfservicepos
    - frontendkitchenmonitor
    - frontendcustomerorderstatus