apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: {{ .Values.dapr.redisHost | quote }}
  - name: redisPassword
    secretKeyRef:
      name: {{ template "fastfood.fullname" . }}-dapr-secrets
      key: redis-password
  - name: redisDB
    value: {{ .Values.dapr.redisDB | default 0  | quote }}
  - name: maxLenApprox
    value: {{ .Values.dapr.maxLenApprox | default 100  | quote }}

# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: pubsub
#   namespace: fastfood
# spec:
#   type: pubsub.rabbitmq
#   version: v1
#   metadata:
#   - name: host
#     value: "amqp://rabbitmq:5672"
#   - name: durable
#     value: "false"
#   - name: deletedWhenUnused
#     value: "false"
#   - name: autoAck
#     value: "false"
#   - name: reconnectWait
#     value: "0"
#   - name: concurrency
#     value: parallel
scopes:
  - orderservice
  - kitchenservice
  - financeservice
  - orderserviceactors
  - frontendselfservicepos
  - frontendkitchenmonitor
  - frontendcustomerorderstatus