<Project>
  <PropertyGroup>
    <ContinuousIntegrationBuild Condition="'$(TF_BUILD)' == 'True' or '$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
