image:
  repository: __azureContainerRegistry__/frontendkitchenmonitor
  tag: __artifactVersion__
  digest: __imageDigest__

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster-staging
  hosts:
    - host: kitchenmonitor.fastfood.__namespace__.aksdemo.4tecture.ch
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - secretName: frontendkitchenmonitor-tls
      hosts:
        - kitchenmonitor.fastfood.__namespace__.aksdemo.4tecture.ch
